on:
  push:
    branches: [main]
  pull_request:
name: Build flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: me.ppvan.psequel.flatpak
        manifest-path: pkgs/flatpak/me.ppvan.psequel.yml
        cache-key: flatpak-builder-${{ github.sha }}
